services:
  - type: web
    name: pathpilot-backend
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: NODE_ENV
        value: production

  - type: web
    name: pathpilot-frontend
    runtime: static
    buildCommand: cd client && npm install && REACT_APP_API_URL=https://pathpilot-backend.onrender.com npm run build
    staticPublishPath: client/build
    envVars:
      - key: NODE_ENV
        value: production 