services:
  - type: web
    name: pathpilot-backend
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: NODE_ENV
        value: production

  - type: web
    name: pathpilot-frontend
    env: static
    buildCommand: |
      cd client
      rm -rf node_modules package-lock.json
      npm install
      NODE_ENV=production CI=false npm run build
    staticPublishPath: ./client/build
    envVars:
      - key: REACT_APP_API_URL
        value: https://pathpilot-backend.onrender.com
      - key: NODE_ENV
        value: production 